{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my.adpoymer",
    "module": "beauty",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "beauty-1.0.0.aar",
          "url": "beauty-1.0.0.aar",
          "size": 22001,
          "sha512": "a4b51e8081fa47723330479e284a185bf9fcc25b9354a01591999d50be7f35a62ae67e8ca4d20d45dceed202b4091a9d36524a2ea00af3c6c443a3ae232495ec",
          "sha256": "14eab97195681ed91fa216ab2c58983aae6106066bccc8f2dc01f439eb2d5512",
          "sha1": "f428602a6ffb6e4b40304d39cf863dd696e58936",
          "md5": "48aa49ed236199f85688c5d88a7d8be2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.my.adpoymer",
          "module": "tailor",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "21.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "beauty-1.0.0.aar",
          "url": "beauty-1.0.0.aar",
          "size": 22001,
          "sha512": "a4b51e8081fa47723330479e284a185bf9fcc25b9354a01591999d50be7f35a62ae67e8ca4d20d45dceed202b4091a9d36524a2ea00af3c6c443a3ae232495ec",
          "sha256": "14eab97195681ed91fa216ab2c58983aae6106066bccc8f2dc01f439eb2d5512",
          "sha1": "f428602a6ffb6e4b40304d39cf863dd696e58936",
          "md5": "48aa49ed236199f85688c5d88a7d8be2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beauty-1.0.0-sources.jar",
          "url": "beauty-1.0.0-sources.jar",
          "size": 8828,
          "sha512": "2d9a3e1fbde5d9b887be24a9aad456d12d3202ec6b9004043f35f750a629a90eaa09180651095e44f2e937a1941ab34d955d43097968d4497bdd89dd6e780136",
          "sha256": "66128780bee3cdce7ea7c0a7ebeec6593f5a9de09fd45f4d202b04301893e87d",
          "sha1": "5ec5b3d8f6db9000a8d2312782480b028d2c4de5",
          "md5": "4c2218c0dc9ca9c733b936d655a808f8"
        }
      ]
    }
  ]
}
