{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my.adpoymer",
    "module": "beauty",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.my.adpoymer",
          "module": "tailor",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": null,
          "module": "hr-sdk_1.5.0.1_release",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hr-sdk_1.5.0.1_release",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "21.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "beauty-1.0.2.aar",
          "url": "beauty-1.0.2.aar",
          "size": 21985,
          "sha512": "619dfcd65745140dc2d3a44f9cace8f8348f9045b50a242f14887128f369377ea95a95644982fe1518c910eac23c92f8860468ed5fc03419b581ede81c906b7a",
          "sha256": "ee9c61141822748eb0878dc7c2924a36118f70a58aa1f1ef5f4e889d0824a2af",
          "sha1": "4575215b867c88a193de7f3e2f96ccdae3632d44",
          "md5": "44b9094466340fbade054f4bf4d99d8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.my.adpoymer",
          "module": "tailor",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": null,
          "module": "hr-sdk_1.5.0.1_release",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hr-sdk_1.5.0.1_release",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "21.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "beauty-1.0.2.aar",
          "url": "beauty-1.0.2.aar",
          "size": 21985,
          "sha512": "619dfcd65745140dc2d3a44f9cace8f8348f9045b50a242f14887128f369377ea95a95644982fe1518c910eac23c92f8860468ed5fc03419b581ede81c906b7a",
          "sha256": "ee9c61141822748eb0878dc7c2924a36118f70a58aa1f1ef5f4e889d0824a2af",
          "sha1": "4575215b867c88a193de7f3e2f96ccdae3632d44",
          "md5": "44b9094466340fbade054f4bf4d99d8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beauty-1.0.2-sources.jar",
          "url": "beauty-1.0.2-sources.jar",
          "size": 8816,
          "sha512": "ee000daf782cabc458f949387a828ae97ef73fdebf1cc9011e0a09e6435f0ee4a04fb5aced54774789a4d0bc9bf0579586ff3fc21f9d1453b5d9a59ef2fd1a38",
          "sha256": "42acf95391bdbe331f8f985510aa9660516204c0a23ebb4eef2071bd7546af2b",
          "sha1": "46cb153284e9086122ba70f0cc06fdb0a9e8d089",
          "md5": "49b27e5f31b96ffe388bd28c483c389c"
        }
      ]
    }
  ]
}
