{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my.adpoymer",
    "module": "tailor",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tailor-1.0.1.aar",
          "url": "tailor-1.0.1.aar",
          "size": 57208,
          "sha512": "93dc1b14a6d094004d74a0e9a3d08c602e1918676f7c4e221f5f6da0f83a694f0dbe3b01031b53daf16e1df5ab32c36c3f0b71091c4b651342dbd747c15eab3c",
          "sha256": "a0ea610e571db499a8c15437d7a8f1a95c9a14b27e09d12f2be6464a4f29875e",
          "sha1": "716e649e2a6fcc9650e7d9f94f8a424e826c89b9",
          "md5": "e30aec24c1540454b1fcc074027f3c39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "tailor-1.0.1.aar",
          "url": "tailor-1.0.1.aar",
          "size": 57208,
          "sha512": "93dc1b14a6d094004d74a0e9a3d08c602e1918676f7c4e221f5f6da0f83a694f0dbe3b01031b53daf16e1df5ab32c36c3f0b71091c4b651342dbd747c15eab3c",
          "sha256": "a0ea610e571db499a8c15437d7a8f1a95c9a14b27e09d12f2be6464a4f29875e",
          "sha1": "716e649e2a6fcc9650e7d9f94f8a424e826c89b9",
          "md5": "e30aec24c1540454b1fcc074027f3c39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tailor-1.0.1-sources.jar",
          "url": "tailor-1.0.1-sources.jar",
          "size": 50159,
          "sha512": "6300edfc1ec1a3d790fa48ae2896b184e2bc78546f9aef9c407992e58ef267cd96cc7acaec8f2fa9c4377ec98fc164710cd5f00a7d58cb0eb68f4f1921bf1aa2",
          "sha256": "07bb45a8361fe79025bb2ea4643ba2ad6f67fd520603123978348fceac17ae73",
          "sha1": "cad8fcc5899062ca2e65f7a05ccfe8106eb0f214",
          "md5": "1777713cdc1acacd45b34d8b2437f11d"
        }
      ]
    }
  ]
}
