{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my",
    "module": "overseas",
    "version": "14.9.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overseas-14.9.20.1.aar",
          "url": "overseas-14.9.20.1.aar",
          "size": 26167,
          "sha512": "644408aa619738e295a1b3c05cb6e1bb028b848bef3b6d02f578d3a11f48ebfe1cefc735a4718781e70263fe743be282c3b6cabeaf29fa422047d99f94383e1e",
          "sha256": "d642082c93d224358a0dc5dd741dca220d23e83cda388a093a02c9f160fbf321",
          "sha1": "2b9eacaad9221085e8a86ca2d3e11b22775a28c8",
          "md5": "cff3d43c3a212bddbbe4cc70fbcd1cde"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "overseas-14.9.20.1.aar",
          "url": "overseas-14.9.20.1.aar",
          "size": 26167,
          "sha512": "644408aa619738e295a1b3c05cb6e1bb028b848bef3b6d02f578d3a11f48ebfe1cefc735a4718781e70263fe743be282c3b6cabeaf29fa422047d99f94383e1e",
          "sha256": "d642082c93d224358a0dc5dd741dca220d23e83cda388a093a02c9f160fbf321",
          "sha1": "2b9eacaad9221085e8a86ca2d3e11b22775a28c8",
          "md5": "cff3d43c3a212bddbbe4cc70fbcd1cde"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overseas-14.9.20.1-sources.jar",
          "url": "overseas-14.9.20.1-sources.jar",
          "size": 12123,
          "sha512": "d84c5733a42386ddcbe255d53267e8bde6adb91fda967cc226514cf88b2be800f7a580c9fc9957130ad11742b1e9ed47c6159072d7df0ba612a3a36ba604de51",
          "sha256": "31c28063875eb18b2c46ce79652724c34283806107a25386482fa1fb4ceb2921",
          "sha1": "ccedb6185e87957ec2ca2b498a3ac1f42da98cec",
          "md5": "df512daa4975c64156903781b9a83972"
        }
      ]
    }
  ]
}
