{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my",
    "module": "overseas",
    "version": "14.4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overseas-14.4.0.1.aar",
          "url": "overseas-14.4.0.1.aar",
          "size": 27066,
          "sha512": "3b22cf7f394d08302d817dccdf13923dc42a697398332ff135ed7b612378b188251f5685dbd86acc229b070e6eecdddac5d857fcbcef221bd356307c3d0e1b65",
          "sha256": "7c90209f10fd8d271eb72153f7d2ea644e921c7663908e32eeb7051fbe2e91d8",
          "sha1": "2d0380a290bedaa3f2b5feb61196ccc058f79f90",
          "md5": "90f1825bdcf8610ae33d12d70daaae81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "14.4.0.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.4.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.14.4.0.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.20.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-facebook",
          "version": {
            "requires": "1.14.4.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-adcolony",
          "version": {
            "requires": "4.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-pangle",
          "version": {
            "requires": "19.14.4.0.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "pag-sdk",
          "version": {
            "requires": "7.2.0.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-unity",
          "version": {
            "requires": "5.14.4.0.1"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mintegralx_overseas",
          "version": {
            "requires": "18.14.4.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbridge_android_sdk",
          "version": {
            "requires": "16.9.71"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-vunglex",
          "version": {
            "requires": "7.14.4.0.1"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.5.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.14.4.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.14.4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "overseas-14.4.0.1.aar",
          "url": "overseas-14.4.0.1.aar",
          "size": 27066,
          "sha512": "3b22cf7f394d08302d817dccdf13923dc42a697398332ff135ed7b612378b188251f5685dbd86acc229b070e6eecdddac5d857fcbcef221bd356307c3d0e1b65",
          "sha256": "7c90209f10fd8d271eb72153f7d2ea644e921c7663908e32eeb7051fbe2e91d8",
          "sha1": "2d0380a290bedaa3f2b5feb61196ccc058f79f90",
          "md5": "90f1825bdcf8610ae33d12d70daaae81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overseas-14.4.0.1-sources.jar",
          "url": "overseas-14.4.0.1-sources.jar",
          "size": 12121,
          "sha512": "6a2ea73551d4e168190edacce87553517288778731e40d87d94508887793aa9d06c2d61958a6f9471654235b4b9c8362b9b283bc42835172b54746c72494a406",
          "sha256": "e1e2e02870ce58e999738335fc0559c5f859fba37e308256f12effe56c982b78",
          "sha1": "2134dbd925a9a0d399357d255d873e6cebf725c6",
          "md5": "f2494d8d40ce691dec73e4c5458064b9"
        }
      ]
    }
  ]
}
