{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my",
    "module": "overseas",
    "version": "9.9.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overseas-9.9.9.0.aar",
          "url": "overseas-9.9.9.0.aar",
          "size": 27067,
          "sha512": "a666f832cf3f97af4c686cbdcb3b753ae0c47bad7e3393ddaa94014d2d0a0db43e21b3a94c2bb57abe98335af8838395ee362f3d18f8cb6e8d6fcc837db2b438",
          "sha256": "ad80dee8bd0e21fef91c98993a641dd8c87ac45465cb407ad4ef5e28ad8bce8a",
          "sha1": "99d907e22106a68249f3f6e72747937697efd5e4",
          "md5": "02c7f56d0292d2cb63f72a23bc4680dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "14.4.0.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.4.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.14.4.0.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.20.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-facebook",
          "version": {
            "requires": "1.14.4.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-adcolony",
          "version": {
            "requires": "4.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-pangle",
          "version": {
            "requires": "19.14.4.0.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "pag-sdk",
          "version": {
            "requires": "7.2.0.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-unity",
          "version": {
            "requires": "5.14.4.0.1"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mintegralx_overseas",
          "version": {
            "requires": "18.14.4.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-vunglex",
          "version": {
            "requires": "7.14.4.0.1"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.5.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.14.4.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.14.4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "overseas-9.9.9.0.aar",
          "url": "overseas-9.9.9.0.aar",
          "size": 27067,
          "sha512": "a666f832cf3f97af4c686cbdcb3b753ae0c47bad7e3393ddaa94014d2d0a0db43e21b3a94c2bb57abe98335af8838395ee362f3d18f8cb6e8d6fcc837db2b438",
          "sha256": "ad80dee8bd0e21fef91c98993a641dd8c87ac45465cb407ad4ef5e28ad8bce8a",
          "sha1": "99d907e22106a68249f3f6e72747937697efd5e4",
          "md5": "02c7f56d0292d2cb63f72a23bc4680dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overseas-9.9.9.0-sources.jar",
          "url": "overseas-9.9.9.0-sources.jar",
          "size": 12118,
          "sha512": "8741a34c61e33d17231324bfc28d810c68852ba4f283ee4a0efaad721b3e6a41fd0164a754d0240ad51722cbf9e13a303a0f529c881317bbb5a0d9a9f818da0e",
          "sha256": "cc7cd019f6739c5a42fe6652bc3c7e887eb49eb3e4a479766404359b1c2ec5f8",
          "sha1": "d7d8f09c5c0a34b69ac8fd6859afcb6a02b8b89b",
          "md5": "95364dcf343e14c79ed7c570e06b3d4d"
        }
      ]
    }
  ]
}
