{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my",
    "module": "overseas",
    "version": "14.4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overseas-14.4.0.2.aar",
          "url": "overseas-14.4.0.2.aar",
          "size": 27063,
          "sha512": "b766fb766e7fb70b056215812d9615127933b969b8f2cac5f37689df05051b1dd05e75b09506e3c57c2299c3cac2b13908b74c3583309d7727d9f4e5133077c3",
          "sha256": "c0bfbf66af50427d402e65de3c38886d73dfd6aae17fc6001611d528a8700b74",
          "sha1": "cadeb8f03b53fb34b566b56a6db031d8afc19472",
          "md5": "da3ad9240fcfc86407c3ebbd367e0ae3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "14.4.0.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.4.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.14.4.0.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.20.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-facebook",
          "version": {
            "requires": "1.14.4.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-adcolony",
          "version": {
            "requires": "4.14.4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-pangle",
          "version": {
            "requires": "19.14.4.0.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "pag-sdk",
          "version": {
            "requires": "7.2.0.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-unity",
          "version": {
            "requires": "5.14.4.0.1"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mintegralx_overseas",
          "version": {
            "requires": "18.14.4.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-vunglex",
          "version": {
            "requires": "7.14.4.0.1"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.5.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.14.4.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.14.4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "overseas-14.4.0.2.aar",
          "url": "overseas-14.4.0.2.aar",
          "size": 27063,
          "sha512": "b766fb766e7fb70b056215812d9615127933b969b8f2cac5f37689df05051b1dd05e75b09506e3c57c2299c3cac2b13908b74c3583309d7727d9f4e5133077c3",
          "sha256": "c0bfbf66af50427d402e65de3c38886d73dfd6aae17fc6001611d528a8700b74",
          "sha1": "cadeb8f03b53fb34b566b56a6db031d8afc19472",
          "md5": "da3ad9240fcfc86407c3ebbd367e0ae3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overseas-14.4.0.2-sources.jar",
          "url": "overseas-14.4.0.2-sources.jar",
          "size": 12121,
          "sha512": "81b86977c49a34d7e6e52184e8f38f3eb276c8f03b5dac76ae944bbddfe75d493820640ad896704c20a27459943d5ce1787b9999e330d3b0611c368be48080cb",
          "sha256": "cd09cd4e08dc2d7c47d893f8c396b6fd574899da68e69ae1f144f3b834428a49",
          "sha1": "c788cad3403ced0bf729999d48b1d376b8b58685",
          "md5": "41c177317f23116f670bec773284cbf3"
        }
      ]
    }
  ]
}
