{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my",
    "module": "overseas",
    "version": "13.4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overseas-13.4.20.1.aar",
          "url": "overseas-13.4.20.1.aar",
          "size": 27044,
          "sha512": "addfdbc7f5f6bb492754b89e5a036edf958aa21a7a1e9b8ac0f7a194c4f5f305afc8629cc28c63cec07ea7c57453f925370e364dcbf8d210cf67debe1dba8f26",
          "sha256": "55e46a83542bb7cffc36eaf630174cc99e44c069f7a7833891d79778fa76cb46",
          "sha1": "d71ab1dffefebeca0c02d1763e09feffd6c6c0f6",
          "md5": "4b37846ee9cf49dc88177ae8c4d6efb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "13.4.20.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.13.4.20.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.18.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-facebook",
          "version": {
            "requires": "1.13.4.20.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.13.4.20.1"
          }
        },
        {
          "group": "com.tapjoy",
          "module": "tapjoy-android-sdk",
          "version": {
            "requires": "13.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tapjoy-android-sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-tapjoy",
          "version": {
            "requires": "6.13.4.20.1"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-adcolony",
          "version": {
            "requires": "4.13.4.20.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-pangle",
          "version": {
            "requires": "19.13.4.20.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "6.4.0.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-unity",
          "version": {
            "requires": "5.13.4.20.1"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mintegralx_overseas",
          "version": {
            "requires": "18.13.4.20.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbridge_android_sdk",
          "version": {
            "requires": "16.9.11"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-vunglex",
          "version": {
            "requires": "7.13.4.20.1"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.4.3"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.13.4.20.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.13.6.10.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "overseas-13.4.20.1.aar",
          "url": "overseas-13.4.20.1.aar",
          "size": 27044,
          "sha512": "addfdbc7f5f6bb492754b89e5a036edf958aa21a7a1e9b8ac0f7a194c4f5f305afc8629cc28c63cec07ea7c57453f925370e364dcbf8d210cf67debe1dba8f26",
          "sha256": "55e46a83542bb7cffc36eaf630174cc99e44c069f7a7833891d79778fa76cb46",
          "sha1": "d71ab1dffefebeca0c02d1763e09feffd6c6c0f6",
          "md5": "4b37846ee9cf49dc88177ae8c4d6efb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overseas-13.4.20.1-sources.jar",
          "url": "overseas-13.4.20.1-sources.jar",
          "size": 12087,
          "sha512": "21cbb81ff7e3522ef993d51a98c45ce3fb5ad0c49eb32712fb0a087eb3f5b9c04553ce4142fe94310589bcab8fd1d3602ec65215ef6aef4af63b28e246c128fa",
          "sha256": "248c76cbefb824dbf1e5f2c93c1876c135e48704c2b849fd89a62cf9845a608d",
          "sha1": "50b089e79286ecb3e34fca87b4f11acee0bd453f",
          "md5": "b296034cc826718ea49fde9806d2dd63"
        }
      ]
    }
  ]
}
