{
  "formatVersion": "1.1",
  "component": {
    "group": "com.my.adpoymer",
    "module": "core",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.my.adpoymer",
          "module": "tailor",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.my.adpoymer",
          "module": "beauty",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.1.aar",
          "url": "core-1.0.1.aar",
          "size": 1539,
          "sha512": "b14af06169341442a3f3569c03ad9cacdd6bd24326a136b80a44b6f5348bab8862713646a733da6b7137e62ea8620059fda18561ff50ab84a4080fb74a417d4a",
          "sha256": "e49e61762f278e75f90d7c02a27e400c9c84830cb24607bcbd96ac32641252c7",
          "sha1": "c60af633512e7d38cd5f377ac8ed97fa41846412",
          "md5": "2300daf0462e3b4830c8bc586efafe52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.my.adpoymer",
          "module": "tailor",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.my.adpoymer",
          "module": "beauty",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.1.aar",
          "url": "core-1.0.1.aar",
          "size": 1539,
          "sha512": "b14af06169341442a3f3569c03ad9cacdd6bd24326a136b80a44b6f5348bab8862713646a733da6b7137e62ea8620059fda18561ff50ab84a4080fb74a417d4a",
          "sha256": "e49e61762f278e75f90d7c02a27e400c9c84830cb24607bcbd96ac32641252c7",
          "sha1": "c60af633512e7d38cd5f377ac8ed97fa41846412",
          "md5": "2300daf0462e3b4830c8bc586efafe52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.1-sources.jar",
          "url": "core-1.0.1-sources.jar",
          "size": 1156,
          "sha512": "70d07b5ce97f15bf824160e6fb2feecf4856686e3a4252697e5e5a7f40a847ebdb8be505fd9be6e7f309b38a7eb519f0cf06e4d7388c1b9845baf20ec8e999f3",
          "sha256": "7c9c5bcd252d07c8fe1a20ab9ded89384aac20e47bd4628fc42a1e24141021b2",
          "sha1": "c065f0d409c261cfeb4bac41fe88b54f0c0e21a1",
          "md5": "36c6de4345d50c04197e0b321095cbb6"
        }
      ]
    }
  ]
}
